### ISSUE TITLE
JAVA_HOME not defined

### ISSUE THREAD

**Issue by bandanagyrl** [AbdElraoufSabri/LynCrypto#1]
Sorry I am new to all this. I followed all the steps and copied the directory and entered the double \\ as indicated but I keep getting the same error when I run the run.bat file. Suggestions?

I checked and I am currently running Java 8.12

**Comment by abd3lraouf** [comment]
Sorry, for being so late.

What is the exact error message ?
can you check that JAVA_HOME variable is already set in environment variables ?
